---
title: Tenaga Pendidik (Dosen)
author: Riana Hadiana
date: '2020-03-04'
slug: tenaga-pendidik-dosen
categories: []
tags: []
lastmod: '2020-03-04T14:46:29+07:00'
layout: post
type: post
highlight: no
---

**Insert Lead paragraph here.**

Saat ini Universitas Sultan Ageng Tirtayasa memiliki 619 dosen PNS dan 148 dosen non PNS.

## Dosen PNS

Dosen PNS Untirta tersebar di 6 Fakultas, di antaranya :

* Fkultas Hukum (52)
* FKIP (174)
* Fakultas Teknik (138)
* Fakultas Pertanian (70)
* Fakultas Ekonomi dan Bisnis (109)
* FISIP (57)
* Fakultas Kedokteran (19)

Sebaran lengkap dosen PNS di Untirta bisa dilihat pada diagram berikut.

Berikut adalah daftar dosen PNS di Universitas Sultan Ageng Tirtayasa.

```{r, echo=FALSE}
dosen <- read.csv("dosen.csv", sep = ";")
DT::datatable(dosen[,c(1, 3, 4, 7:9)])
```

### Heading 3

At quisque litora ullamcorper maecenas ultricies ut dignissim luctus curabitur, cras congue eget primis aliquam fringilla nulla dictum posuere, vestibulum sit magnis nisl praesent eros ipsum nunc. Ligula lacus ipsum orci aenean integer pharetra habitasse interdum, porttitor etiam hac feugiat placerat morbi posuere turpis leo, quam at amet gravida commodo fringilla erat.
